### PR TITLE
feat: lets enable /jx chatops commands by default

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by hervelemeur** [comment]
@rawlingsj So, we can use another word than "jx" if wanted?

**Comment by rawlingsj** [comment]
> So, we can use another word than "jx" if wanted?

Yeah!  If you wanted to enable your own command prefix and trigger presubmit jobs with that you can override that value.

I.e. setting `customDeploymentTriggerCommand: foo`

you can then add a presubmit job to  ./lighthouse/trigger.yaml that uses a `trigger: /foo`

We plan on rolling out a number of `/jx preview`, `/jx foo` commands, building out the developer UX for Chatops on PRs

**Comment by rawlingsj** [comment]
fwiw right now in lighthouse you can only specify one extra command, it might be worth considering changing that value to handle multiple commands so folks can add their own and still use `/jx` ones

**Pull request merged**
