### PR TITLE
fix: provide flag to supress template output

### LINKED ISSUE #1237: Pass log level flag to helmfile
See: https://github.com/jenkins-x/jx-admin/issues/51

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes #1237 
fixes https://github.com/jenkins-x/jx-admin/issues/51

### CODE REVIEW

**Comment by ankitm123** [comment]
@jstrachan the kind tests failing is not related to this PR, it seems (btw, nice to see github actions :+1: )

**Comment by jstrachan** [comment]
gonna close this as we've fixed it inside jx-gitops now

**Pull request closed without merging**
